#!/usr/bin/env bash
set -euo pipefail

# Regenerate .env from provisioning template and do a full clean restart.
# Use this instead of manual sed patches when config is out of date.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE="${WORKSPACE:-/workspace}"
MODELS_DIR="${MODELS_DIR:-$WORKSPACE/models}"
VLLM_PORT=8787

echo "[regen] Regenerating .env from latest template..."
cat > "$APP_DIR/.env" <<ENVEOF
# Generated by regenerate_env_and_restart.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

RAG_LLM_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_MODEL=Qwen/Qwen3-30B-A3B
RAG_LLM_FAST_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_FAST_MODEL=Qwen/Qwen3-30B-A3B

SENSEVOICE_BASE_URL=http://127.0.0.1:50000
SENSEVOICE_API_STYLE=compat
COSYVOICE_BASE_URL=http://127.0.0.1:50001
COSYVOICE_API_STYLE=compat

WHISPER_BASE_URL=http://127.0.0.1:50002
WHISPER_DEVICE=cuda
WHISPER_COMPUTE_TYPE=float16

QWEN3_TTS_BASE_URL=http://127.0.0.1:50003
QWEN3_ASR_BASE_URL=http://127.0.0.1:50004
VOXTRAL_BASE_URL=http://127.0.0.1:50005
QWEN3_OMNI_BASE_URL=http://127.0.0.1:8002

STACK_MODE=docker
RAG_LAUNCH_MODE=supervisor
STACK_VOICE_PROFILE=oss_russian

STACK_QWEN_CMD="./.venv/bin/python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3-30B-A3B --port ${VLLM_PORT} --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.75 --download-dir ${MODELS_DIR}"
STACK_SENSEVOICE_CMD="./.venv-sensevoice/bin/python -m uvicorn services.sensevoice_server:app --host 0.0.0.0 --port 50000"
STACK_COSYVOICE_CMD="./.venv-voice-oss/bin/python -m uvicorn services.vosk_tts_server:app --host 0.0.0.0 --port 50001"
STACK_WHISPER_CMD="LD_LIBRARY_PATH=./.venv-voice-oss/lib/python3.12/site-packages/nvidia/cublas/lib:./.venv-voice-oss/lib/python3.12/site-packages/nvidia/cudnn/lib:\${LD_LIBRARY_PATH:-} ./.venv-voice-oss/bin/python -m uvicorn services.whisper_server:app --host 0.0.0.0 --port 50002"
STACK_QWEN3_TTS_CMD="./.venv-qwen3-tts/bin/python -m uvicorn services.qwen3_tts_server:app --host 0.0.0.0 --port 50003"
STACK_QWEN3_ASR_CMD="./.venv-qwen3-asr/bin/python -m uvicorn services.qwen3_asr_server:app --host 0.0.0.0 --port 50004"
STACK_VOXTRAL_CMD="./.venv-voxtral/bin/python -m uvicorn services.voxtral_server:app --host 0.0.0.0 --port 50005"
STACK_QWEN3_OMNI_CMD="./.venv-qwen3-omni/bin/python -m uvicorn services.qwen3_omni_server:app --host 0.0.0.0 --port 8002"

HF_HOME=${MODELS_DIR}
ENVEOF

echo "[regen] .env written. Running full restart..."
bash "$SCRIPT_DIR/restart_all.sh"
