#!/usr/bin/env bash
set -euo pipefail

# Regenerate .env from provisioning template and do a full clean restart.
# Use this instead of manual sed patches when config is out of date.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Prefer an explicit MODELS_DIR. Otherwise look for an existing HF hub cache in
# known locations so the regen does not silently point HF_HOME at an empty dir.
if [ -z "${MODELS_DIR:-}" ]; then
  for candidate in /ephemeral/models /workspace/models "$HOME/models"; do
    if [ -d "$candidate/hub" ]; then
      MODELS_DIR="$candidate"
      break
    fi
  done
fi
# Fallback to the old derivation if no cache was found yet (fresh machine).
if [ -z "${MODELS_DIR:-}" ]; then
  if [ -n "${WORKSPACE:-}" ]; then :; elif [ -d "/ephemeral" ]; then WORKSPACE="/ephemeral"; elif [ -d "/workspace" ]; then WORKSPACE="/workspace"; else WORKSPACE="$HOME"; fi
  MODELS_DIR="$WORKSPACE/models"
fi
echo "[regen] Using MODELS_DIR=${MODELS_DIR}"
VLLM_PORT=8787
SESSIONAGENT_PORT=8788

# Model revision pinning (override via env: QWEN_MAIN_REVISION=... QWEN_SESSIONAGENT_REVISION=...)
QWEN_MAIN_REV_FLAG=""
QWEN_SESSIONAGENT_REV_FLAG=""
[ -n "${QWEN_MAIN_REVISION:-}" ] && QWEN_MAIN_REV_FLAG="--revision ${QWEN_MAIN_REVISION}"
[ -n "${QWEN_SESSIONAGENT_REVISION:-}" ] && QWEN_SESSIONAGENT_REV_FLAG="--revision ${QWEN_SESSIONAGENT_REVISION}"

# Auto-detect GPU memory and set optimal vLLM utilization for main + sessionagent
GPU_MIB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
GPU_GB=$(( ${GPU_MIB:-0} / 1024 ))
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | tr -d ' ')

if [ "$GPU_GB" -ge 120 ]; then
  GPU_UTIL="0.68"; SESSIONAGENT_GPU_UTIL="0.10"
elif [ "$GPU_GB" -ge 90 ]; then
  GPU_UTIL="0.62"; SESSIONAGENT_GPU_UTIL="0.11"
elif [ "$GPU_GB" -ge 75 ]; then
  GPU_UTIL="0.60"; SESSIONAGENT_GPU_UTIL="0.12"  # 48GB main + 9.6GB SA = 57.6GB
else
  GPU_UTIL="0.55"; SESSIONAGENT_GPU_UTIL="0.00"  # SA disabled on small GPU
fi

echo "[regen] GPU: ${GPU_NAME} ${GPU_GB}GB -> main ${GPU_UTIL}, sessionagent ${SESSIONAGENT_GPU_UTIL}"

if [ "$SESSIONAGENT_GPU_UTIL" = "0.00" ]; then
  SA_ENV_LINES=$'\n'"# SessionAgent disabled on small GPU (falls back to main LLM)"$'\n'"SESSIONAGENT_BASE_URL="$'\n'"SESSIONAGENT_MODEL="
  SA_CMD_LINE='STACK_SESSIONAGENT_CMD=""'
else
  SA_ENV_LINES=$'\n'"SESSIONAGENT_BASE_URL=http://127.0.0.1:${SESSIONAGENT_PORT}/v1"$'\n'"SESSIONAGENT_MODEL=Qwen/Qwen3-4B-Instruct-2507-FP8"
  SA_CMD_LINE="STACK_SESSIONAGENT_CMD=\"./.venv/bin/python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3-4B-Instruct-2507-FP8 ${QWEN_SESSIONAGENT_REV_FLAG} --port ${SESSIONAGENT_PORT} --dtype bfloat16 --max-model-len 4096 --gpu-memory-utilization ${SESSIONAGENT_GPU_UTIL} --enable-prefix-caching --download-dir ${MODELS_DIR}\""
fi
echo "[regen] Regenerating .env from latest template..."

# Preserve tool-use credentials across regenerations. We read from exported env
# vars first (so the operator can `export ... && bash regenerate_...`), and fall
# back to whatever is already in .env (so re-running the regen does not wipe
# previously-set tokens). Empty defaults for the CRM block since it is still
# pending from the client.
_env_get() {
  local key="$1"; local default_val="${2:-}"
  if [ -n "${!key:-}" ]; then
    printf '%s' "${!key}"
  elif [ -f "$APP_DIR/.env" ]; then
    local line
    line=$(grep -E "^${key}=" "$APP_DIR/.env" | tail -1 || true)
    printf '%s' "${line#*=}" | sed -E "s/^'(.*)'\$/\1/; s/^\"(.*)\"\$/\1/"
  else
    printf '%s' "$default_val"
  fi
}
CALCULATOR_API_BASE_URL_V="$(_env_get CALCULATOR_API_BASE_URL 'https://personal.mikro-leasing.by/calculator/api')"
CALCULATOR_API_TOKEN_V="$(_env_get CALCULATOR_API_TOKEN '')"
USD_BYN_RATE_V="$(_env_get USD_BYN_RATE '3.0')"
SMS_API_LOGIN_V="$(_env_get SMS_API_LOGIN '')"
SMS_API_PASSWORD_V="$(_env_get SMS_API_PASSWORD '')"
SMS_SENDER_NAME_V="$(_env_get SMS_SENDER_NAME 'MikroLizing')"
CRM_WEBHOOK_URL_V="$(_env_get CRM_WEBHOOK_URL '')"
CRM_WEBHOOK_TOKEN_V="$(_env_get CRM_WEBHOOK_TOKEN '')"

cat > "$APP_DIR/.env" <<ENVEOF
# Generated by regenerate_env_and_restart.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# GPU: ${GPU_NAME} ${GPU_GB}GB -- vLLM utilization: ${GPU_UTIL}
# Whisper STT + Silero TTS + Qwen3.5-35B-A3B-FP8

RAG_LLM_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_MODEL=Qwen/Qwen3.5-35B-A3B-FP8
RAG_LLM_FAST_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_FAST_MODEL=Qwen/Qwen3.5-35B-A3B-FP8
${SA_ENV_LINES}

WHISPER_BASE_URL=http://127.0.0.1:50002
WHISPER_DEVICE=cuda
WHISPER_COMPUTE_TYPE=float16

SILERO_TTS_BASE_URL=http://127.0.0.1:50006
SILERO_TTS_SPEAKER=xenia
SILERO_TTS_MODEL=v5_4_ru
SILERO_TTS_SAMPLE_RATE=24000

VAD_SILENCE_MS=500
SILERO_VAD_PATH=./models/silero_vad.jit

STACK_MODE=docker
RAG_LAUNCH_MODE=supervisor
STACK_VOICE_PROFILE=oss_russian

STACK_QWEN_CMD="./.venv/bin/python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3.5-35B-A3B-FP8 ${QWEN_MAIN_REV_FLAG} --port ${VLLM_PORT} --dtype bfloat16 --max-model-len 32768 --gpu-memory-utilization ${GPU_UTIL} --download-dir ${MODELS_DIR} --enable-auto-tool-choice --tool-call-parser qwen3_xml"
${SA_CMD_LINE}
STACK_WHISPER_CMD="LD_LIBRARY_PATH=\$(echo ./.venv-voice-oss/lib/python3.*/site-packages/nvidia/cublas/lib):\$(echo ./.venv-voice-oss/lib/python3.*/site-packages/nvidia/cudnn/lib):\${LD_LIBRARY_PATH:-} ./.venv-voice-oss/bin/python -m uvicorn services.whisper_server:app --host 0.0.0.0 --port 50002"
STACK_SILERO_TTS_CMD="./.venv-voice-oss/bin/python -m uvicorn services.silero_tts_server:app --host 0.0.0.0 --port 50006"

HF_HOME=${MODELS_DIR}
HF_HUB_OFFLINE=1
TRANSFORMERS_OFFLINE=1

# ── Tool Use: Calculator API ──
CALCULATOR_API_BASE_URL='${CALCULATOR_API_BASE_URL_V}'
CALCULATOR_API_TOKEN='${CALCULATOR_API_TOKEN_V}'
USD_BYN_RATE=${USD_BYN_RATE_V}

# ── Tool Use: SMS (sms-assistent.by) ──
SMS_API_LOGIN='${SMS_API_LOGIN_V}'
SMS_API_PASSWORD='${SMS_API_PASSWORD_V}'
SMS_SENDER_NAME='${SMS_SENDER_NAME_V}'

# ── Tool Use: CRM Webhook ──
CRM_WEBHOOK_URL='${CRM_WEBHOOK_URL_V}'
CRM_WEBHOOK_TOKEN='${CRM_WEBHOOK_TOKEN_V}'
ENVEOF

echo "[regen] Tool-use credentials: calculator=$([ -n "$CALCULATOR_API_TOKEN_V" ] && echo SET || echo empty), sms=$([ -n "$SMS_API_LOGIN_V" ] && echo SET || echo empty), crm=$([ -n "$CRM_WEBHOOK_URL_V" ] && echo SET || echo empty)"

echo "[regen] .env written. Running full restart..."
bash "$SCRIPT_DIR/restart_all.sh"
