#!/usr/bin/env bash
set -euo pipefail

# Regenerate .env from provisioning template and do a full clean restart.
# Use this instead of manual sed patches when config is out of date.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE="${WORKSPACE:-/workspace}"
MODELS_DIR="${MODELS_DIR:-$WORKSPACE/models}"
VLLM_PORT=8787

echo "[regen] Regenerating .env from latest template..."
cat > "$APP_DIR/.env" <<ENVEOF
# Generated by regenerate_env_and_restart.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# H100 NVL 94GB -- Whisper STT + Silero TTS + Qwen3.5-35B-A3B-FP8

RAG_LLM_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_MODEL=Qwen/Qwen3.5-35B-A3B-FP8
RAG_LLM_FAST_BASE_URL=http://127.0.0.1:${VLLM_PORT}/v1
RAG_LLM_FAST_MODEL=Qwen/Qwen3.5-35B-A3B-FP8

WHISPER_BASE_URL=http://127.0.0.1:50002
WHISPER_DEVICE=cuda
WHISPER_COMPUTE_TYPE=float16

SILERO_TTS_BASE_URL=http://127.0.0.1:50006
SILERO_TTS_SPEAKER=baya
SILERO_TTS_SAMPLE_RATE=24000

VAD_SILENCE_MS=500
SILERO_VAD_PATH=./models/silero_vad.jit

STACK_MODE=docker
RAG_LAUNCH_MODE=supervisor
STACK_VOICE_PROFILE=oss_russian

STACK_QWEN_CMD="./.venv/bin/python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3.5-35B-A3B-FP8 --port ${VLLM_PORT} --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.60 --download-dir ${MODELS_DIR}"
STACK_WHISPER_CMD="LD_LIBRARY_PATH=./.venv-voice-oss/lib/python3.12/site-packages/nvidia/cublas/lib:./.venv-voice-oss/lib/python3.12/site-packages/nvidia/cudnn/lib:\${LD_LIBRARY_PATH:-} ./.venv-voice-oss/bin/python -m uvicorn services.whisper_server:app --host 0.0.0.0 --port 50002"
STACK_SILERO_TTS_CMD="./.venv-voice-oss/bin/python -m uvicorn services.silero_tts_server:app --host 0.0.0.0 --port 50006"

HF_HOME=${MODELS_DIR}
ENVEOF

echo "[regen] .env written. Running full restart..."
bash "$SCRIPT_DIR/restart_all.sh"
